### ISSUE TITLE
[Bug] I started seeing node errors: UnhandledPromiseRejectionWarning ..

### ISSUE THREAD

**Issue by ovizii** [joshuaavalon/docker-cloudflare#43]
**Describe the bug**
I start the container and am seeing an error. The container does not seem to work.

**To Reproduce**
Use my docker-compose.yml file and you can reproduce it. I can share it if necessary.

**Expected behavior**
I start the container and it does its job and updates my domains on CF

**Output log**
```
cloudflare-ddns    | Initializing container
cloudflare-ddns    |
cloudflare-ddns    | User uid: 1000
cloudflare-ddns    | User gid: 1000
cloudflare-ddns    |
cloudflare-ddns    | [cont-init.d] 10-adduser: exited 0.
cloudflare-ddns    | [cont-init.d] done.
cloudflare-ddns    | [services.d] starting services
cloudflare-ddns    | [services.d] done.
cloudflare-ddns    | (node:202) UnhandledPromiseRejectionWarning: Error: unknown format "email" ignored in schema at path "#/definitions/globalAuth/properties/email"
cloudflare-ddns    |     at unknownFormat (/app/node_modules/ajv/dist/vocabularies/format/format.js:63:23)
cloudflare-ddns    |     at validateFormat (/app/node_modules/ajv/dist/vocabularies/format/format.js:50:17)
cloudflare-ddns    |     at Object.code (/app/node_modules/ajv/dist/vocabularies/format/format.js:22:13)
cloudflare-ddns    |     at Object.keywordCode (/app/node_modules/ajv/dist/compile/validate/keyword.js:12:13)
cloudflare-ddns    |     at /app/node_modules/ajv/dist/compile/validate/iterate.js:53:27
cloudflare-ddns    |     at CodeGen.code (/app/node_modules/ajv/dist/compile/codegen/index.js:424:13)
cloudflare-ddns    |     at CodeGen.block (/app/node_modules/ajv/dist/compile/codegen/index.js:553:18)
cloudflare-ddns    |     at iterateKeywords (/app/node_modules/ajv/dist/compile/validate/iterate.js:50:9)
cloudflare-ddns    |     at groupKeywords (/app/node_modules/ajv/dist/compile/validate/iterate.js:30:13)
cloudflare-ddns    |     at /app/node_modules/ajv/dist/compile/validate/iterate.js:22:13
cloudflare-ddns    | (Use `node --trace-warnings ...` to show where the warning was created)
cloudflare-ddns    | (node:202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
cloudflare-ddns    | (node:202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
cloudflare-ddns    | (node:227) UnhandledPromiseRejectionWarning: Error: unknown format "email" ignored in schema at path "#/definitions/globalAuth/properties/email"
cloudflare-ddns    |     at unknownFormat (/app/node_modules/ajv/dist/vocabularies/format/format.js:63:23)
cloudflare-ddns    |     at validateFormat (/app/node_modules/ajv/dist/vocabularies/format/format.js:50:17)
cloudflare-ddns    |     at Object.code (/app/node_modules/ajv/dist/vocabularies/format/format.js:22:13)
cloudflare-ddns    |     at Object.keywordCode (/app/node_modules/ajv/dist/compile/validate/keyword.js:12:13)
cloudflare-ddns    |     at /app/node_modules/ajv/dist/compile/validate/iterate.js:53:27
cloudflare-ddns    |     at CodeGen.code (/app/node_modules/ajv/dist/compile/codegen/index.js:424:13)
cloudflare-ddns    |     at CodeGen.block (/app/node_modules/ajv/dist/compile/codegen/index.js:553:18)
cloudflare-ddns    |     at iterateKeywords (/app/node_modules/ajv/dist/compile/validate/iterate.js:50:9)
cloudflare-ddns    |     at groupKeywords (/app/node_modules/ajv/dist/compile/validate/iterate.js:30:13)
cloudflare-ddns    |     at /app/node_modules/ajv/dist/compile/validate/iterate.js:22:13
cloudflare-ddns    | (Use `node --trace-warnings ...` to show where the warning was created)
cloudflare-ddns    | (node:227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
cloudflare-ddns    | (node:227) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Environment:**

- OS: 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

- Docker: 
`Docker version 20.10.2, build 2291f61`

- Version: 
Docker inspect shows this image being used: "Image": `"sha256:12b8327dd319a933acfd483fa016ac92769a21a2fe7985fd89614fe217202b46", `

docker images
```
REPOSITORY                                  TAG                   IMAGE ID       CREATED         SIZE
joshava/cloudflare-ddns                     latest                12b8327dd319   34 hours ago    134MB
```

**Additional context**
Please let me know what other info I can add to help debug this.

**Comment by ovizii** [comment]
oh, seeing that the image has been created 34 hours ago, I assume I should be able to revert to an older tag as it was working just a few days ago. 

Which tag should I use instead of "latest" ?

**Comment by debrunet** [comment]
I have exactly the same problem. Version 2.2.7 works, anything onwards does not.
